// Bootstrap GUI Editor - Complete Component Catalog (Bootstrap 5)

import { BootstrapComponentDefinition, CategoryInfo } from "./types";

export const CATEGORIES: CategoryInfo[] = [
  { id: "layout", label: "Layout", icon: "LayoutGrid" },
  { id: "typography", label: "Tipografia", icon: "Type" },
  { id: "forms", label: "Form", icon: "FileInput" },
  { id: "buttons", label: "Pulsanti", icon: "MousePointerClick" },
  { id: "navigation", label: "Navigazione", icon: "Navigation" },
  { id: "content", label: "Contenuto", icon: "Layers" },
  { id: "tables", label: "Tabelle", icon: "Table" },
  { id: "images", label: "Immagini & Media", icon: "Image" },
  { id: "utilities", label: "Utilità", icon: "Wrench" },
];

export const COMPONENTS: BootstrapComponentDefinition[] = [
  // ──────────────── LAYOUT ────────────────
  {
    type: "container",
    label: "Container",
    category: "layout",
    icon: "Box",
    description: "A basic container for content",
    properties: [
      {
        key: "fluid",
        label: "Type",
        type: "select",
        defaultValue: "fixed",
        options: [
          { label: "Fixed width", value: "fixed" },
          { label: "Fluid (full width)", value: "fluid" },
          { label: "Responsive (sm)", value: "sm" },
          { label: "Responsive (md)", value: "md" },
          { label: "Responsive (lg)", value: "lg" },
          { label: "Responsive (xl)", value: "xl" },
          { label: "Responsive (xxl)", value: "xxl" },
        ],
      },
      {
        key: "bgColor",
        label: "Background",
        type: "select",
        defaultValue: "transparent",
        options: [
          { label: "Transparent", value: "transparent" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "White", value: "white" },
        ],
      },
      {
        key: "padding",
        label: "Padding",
        type: "select",
        defaultValue: "3",
        options: [
          { label: "None", value: "0" },
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
          { label: "5", value: "5" },
        ],
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "select",
        defaultValue: "dark",
        options: [
          { label: "Dark", value: "dark" },
          { label: "White", value: "white" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Muted", value: "muted" },
        ],
      },
      {
        key: "textAlign",
        label: "Allineamento",
        type: "select",
        defaultValue: "start",
        group: "Layout",
        options: [
          { label: "Sinistra", value: "start" },
          { label: "Centro", value: "center" },
          { label: "Destra", value: "end" },
          { label: "Giustificato", value: "justify" },
        ],
      },
    ],
  },
  {
    type: "row",
    label: "Row",
    category: "layout",
    icon: "Columns3",
    description: "A row for grid columns",
    properties: [
      {
        key: "cols",
        label: "Columns",
        type: "select",
        defaultValue: "3",
        options: [
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
          { label: "5", value: "5" },
          { label: "6", value: "6" },
          { label: "7", value: "7" },
          { label: "8", value: "8" },
          { label: "9", value: "9" },
          { label: "10", value: "10" },
          { label: "11", value: "11" },
          { label: "12", value: "12" },
        ],
      },
      {
        key: "gutter",
        label: "Gutter",
        type: "select",
        defaultValue: "0",
        options: [
          { label: "None", value: "0" },
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
          { label: "5", value: "5" },
        ],
      },
      {
        key: "verticalAlign",
        label: "Vertical Align",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Start", value: "start" },
          { label: "Center", value: "center" },
          { label: "End", value: "end" },
        ],
      },
    ],
  },
  {
    type: "col",
    label: "Column",
    category: "layout",
    icon: "RectangleVertical",
    description: "A single grid column",
    hidden: true,
    properties: [
      {
        key: "size",
        label: "Column Width",
        type: "select",
        defaultValue: "auto",
        options: [
          { label: "1/12", value: "1" },
          { label: "2/12", value: "2" },
          { label: "3/12", value: "3" },
          { label: "4/12", value: "4" },
          { label: "5/12", value: "5" },
          { label: "6/12", value: "6" },
          { label: "7/12", value: "7" },
          { label: "8/12", value: "8" },
          { label: "9/12", value: "9" },
          { label: "10/12", value: "10" },
          { label: "11/12", value: "11" },
          { label: "12/12 (full)", value: "12" },
          { label: "Auto", value: "auto" },
        ],
      },
      {
        key: "bgColor",
        label: "Background",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Transparent", value: "transparent" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "White", value: "white" },
        ],
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "select",
        defaultValue: "dark",
        options: [
          { label: "Dark", value: "dark" },
          { label: "White", value: "white" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
        ],
      },
      {
        key: "padding",
        label: "Padding",
        type: "select",
        defaultValue: "3",
        options: [
          { label: "None", value: "0" },
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
          { label: "5", value: "5" },
        ],
      },
      {
        key: "textAlign",
        label: "Allineamento",
        type: "select",
        defaultValue: "start",
        group: "Layout",
        options: [
          { label: "Sinistra", value: "start" },
          { label: "Centro", value: "center" },
          { label: "Destra", value: "end" },
          { label: "Giustificato", value: "justify" },
        ],
      },
    ],
  },

  // ──────────────── TYPOGRAPHY ────────────────
  {
    type: "heading",
    label: "Heading",
    category: "typography",
    icon: "Heading",
    description: "Heading element (h1-h6)",
    properties: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Heading",
        placeholder: "Enter heading text",
      },
      {
        key: "level",
        label: "Level",
        type: "select",
        defaultValue: "2",
        options: [
          { label: "H1", value: "1" },
          { label: "H2", value: "2" },
          { label: "H3", value: "3" },
          { label: "H4", value: "4" },
          { label: "H5", value: "5" },
          { label: "H6", value: "6" },
        ],
      },
      {
        key: "displayClass",
        label: "Display Style",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Normal", value: "" },
          { label: "Display 1", value: "1" },
          { label: "Display 2", value: "2" },
          { label: "Display 3", value: "3" },
          { label: "Display 4", value: "4" },
          { label: "Display 5", value: "5" },
          { label: "Display 6", value: "6" },
        ],
      },
      {
        key: "textColor",
        label: "Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Muted", value: "muted" },
          { label: "White", value: "white" },
        ],
      },
      {
        key: "textAlign",
        label: "Alignment",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
      {
        key: "textClass",
        label: "Font Style",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Normal", value: "" },
          { label: "Italic", value: "fst-italic" },
          { label: "Underline", value: "text-decoration-underline" },
          { label: "Uppercase", value: "text-uppercase" },
          { label: "Lowercase", value: "text-lowercase" },
          { label: "Capitalize", value: "text-capitalize" },
        ],
      },
    ],
  },
  {
    type: "paragraph",
    label: "Paragraph",
    category: "typography",
    icon: "AlignLeft",
    description: "A paragraph of text",
    properties: [
      {
        key: "text",
        label: "Text",
        type: "textarea",
        defaultValue:
          "This is a paragraph of text. You can edit this content in the properties panel on the right.",
        placeholder: "Enter paragraph text",
      },
      {
        key: "lead",
        label: "Lead Style",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "textColor",
        label: "Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Muted", value: "muted" },
        ],
      },
      {
        key: "textAlign",
        label: "Alignment",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
      {
        key: "textSize",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Normal", value: "" },
          { label: "Small (fs-6)", value: "fs-6" },
          { label: "Lead", value: "lead" },
          { label: "Large (fs-4)", value: "fs-4" },
          { label: "Extra Large (fs-2)", value: "fs-2" },
        ],
      },
      {
        key: "bgColor",
        label: "Sfondo",
        type: "select",
        defaultValue: "transparent",
        options: [
          { label: "Trasparente", value: "transparent" },
          { label: "Primario", value: "primary" },
          { label: "Secondario", value: "secondary" },
          { label: "Successo", value: "success" },
          { label: "Pericolo", value: "danger" },
          { label: "Attenzione", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Chiaro", value: "light" },
          { label: "Scuro", value: "dark" },
          { label: "Bianco", value: "white" },
        ],
      },
      {
        key: "padding",
        label: "Spaziatura interna",
        type: "select",
        defaultValue: "2",
        options: [
          { label: "Nessuna", value: "0" },
          { label: "Piccola", value: "1" },
          { label: "Media", value: "2" },
          { label: "Grande", value: "3" },
          { label: "Molto grande", value: "4" },
        ],
      },
      {
        key: "borderRadius",
        label: "Bordi arrotondati",
        type: "select",
        defaultValue: "0",
        options: [
          { label: "Nessuno", value: "0" },
          { label: "Piccolo", value: "4px" },
          { label: "Medio", value: "8px" },
          { label: "Grande", value: "12px" },
          { label: "Pieno", value: "50px" },
        ],
      },
    ],
  },
  {
    type: "blockquote",
    label: "Blockquote",
    category: "typography",
    icon: "TextQuote",
    description: "A blockquote with optional attribution",
    properties: [
      {
        key: "text",
        label: "Quote Text",
        type: "textarea",
        defaultValue:
          "A well-known quote from someone important that adds credibility.",
        placeholder: "Enter quote text",
      },
      {
        key: "attribution",
        label: "Attribution",
        type: "text",
        defaultValue: "Someone Famous",
        placeholder: "Author or source",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
      {
        key: "alignment",
        label: "Alignment",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
    ],
  },
  {
    type: "list",
    label: "List",
    category: "typography",
    icon: "List",
    description: "An ordered or unordered list",
    properties: [
      {
        key: "items",
        label: "Items (one per line)",
        type: "textarea",
        defaultValue: "First item\nSecond item\nThird item\nFourth item\nFifth item",
        placeholder: "One item per line",
      },
      {
        key: "listType",
        label: "List Type",
        type: "select",
        defaultValue: "unordered",
        options: [
          { label: "Unordered (bullets)", value: "unordered" },
          { label: "Ordered (numbers)", value: "ordered" },
          { label: "Unstyled", value: "unstyled" },
        ],
      },
      {
        key: "textColor",
        label: "Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Muted", value: "muted" },
        ],
      },
    ],
  },
  {
    type: "code-block",
    label: "Code Block",
    category: "typography",
    icon: "Code",
    description: "A block of code",
    properties: [
      {
        key: "code",
        label: "Code",
        type: "textarea",
        defaultValue: '&lt;div class="container"&gt;\n  &lt;h1&gt;Hello, world!&lt;/h1&gt;\n&lt;/div&gt;',
        placeholder: "Enter code",
      },
      {
        key: "inline",
        label: "Inline Code",
        type: "boolean",
        defaultValue: false,
        description: "Display as inline code instead of a block",
      },
    ],
  },

  // ──────────────── FORMS ────────────────
  {
    type: "input",
    label: "Input",
    category: "forms",
    icon: "TextCursorInput",
    description: "Text input field",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Email address",
        placeholder: "Field label",
      },
      {
        key: "type",
        label: "Input Type",
        type: "select",
        defaultValue: "text",
        options: [
          { label: "Text", value: "text" },
          { label: "Email", value: "email" },
          { label: "Password", value: "password" },
          { label: "Number", value: "number" },
          { label: "Date", value: "date" },
          { label: "Time", value: "time" },
          { label: "URL", value: "url" },
          { label: "Tel", value: "tel" },
          { label: "Search", value: "search" },
          { label: "Color", value: "color" },
          { label: "Valuta (€)", value: "currency" },
        ],
      },
      {
        key: "text",
        label: "Valore",
        type: "text",
        defaultValue: "",
        placeholder: "Valore del campo",
      },
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "name@example.com",
        placeholder: "Placeholder text",
      },
      {
        key: "helpText",
        label: "Help Text",
        type: "text",
        defaultValue: "We'll never share your email with anyone else.",
        placeholder: "Help text below input",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "readonly",
        label: "Readonly",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "required",
        label: "Required",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "floating",
        label: "Floating Label",
        type: "boolean",
        defaultValue: false,
        description: "Use Bootstrap floating labels",
      },
      {
        key: "plaintext",
        label: "Plaintext",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "textarea",
    label: "Textarea",
    category: "forms",
    icon: "AlignJustify",
    description: "Multi-line text input",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Message",
        placeholder: "Field label",
      },
      {
        key: "text",
        label: "Valore",
        type: "text",
        defaultValue: "",
        placeholder: "Valore del campo",
      },
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "Leave a comment here",
        placeholder: "Placeholder text",
      },
      {
        key: "rows",
        label: "Rows",
        type: "number",
        defaultValue: 3,
      },
      {
        key: "helpText",
        label: "Help Text",
        type: "text",
        defaultValue: "",
        placeholder: "Help text below input",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "select-input",
    label: "Select",
    category: "forms",
    icon: "ChevronDown",
    description: "Dropdown select field",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Select an option",
        placeholder: "Field label",
      },
      {
        key: "options",
        label: "Options (one per line)",
        type: "textarea",
        defaultValue: "Choose...\nOne\nTwo\nThree\nFour\nFive",
        placeholder: "One option per line",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "multiple",
        label: "Multiple Selection",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "checkbox",
    label: "Checkbox",
    category: "forms",
    icon: "CheckSquare",
    description: "Checkbox input",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Check me out",
        placeholder: "Checkbox label",
      },
      {
        key: "checked",
        label: "Checked",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "inline",
        label: "Inline",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "reverse",
        label: "Reverse",
        type: "boolean",
        defaultValue: false,
        description: "Put checkbox on the right",
      },
    ],
  },
  {
    type: "radio",
    label: "Radio Button",
    category: "forms",
    icon: "CircleDot",
    description: "Radio button input",
    properties: [
      {
        key: "name",
        label: "Group Name",
        type: "text",
        defaultValue: "radioGroup",
        placeholder: "Radio group name",
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Select this option",
        placeholder: "Radio label",
      },
      {
        key: "checked",
        label: "Checked",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "inline",
        label: "Inline",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "range",
    label: "Range Slider",
    category: "forms",
    icon: "SlidersHorizontal",
    description: "Range input slider",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Example range",
        placeholder: "Range label",
      },
      {
        key: "min",
        label: "Min",
        type: "number",
        defaultValue: 0,
      },
      {
        key: "max",
        label: "Max",
        type: "number",
        defaultValue: 100,
      },
      {
        key: "defaultValue",
        label: "Default Value",
        type: "number",
        defaultValue: 50,
      },
      {
        key: "step",
        label: "Step",
        type: "number",
        defaultValue: 1,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "switch",
    label: "Switch",
    category: "forms",
    icon: "ToggleLeft",
    description: "Toggle switch input",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Toggle switch",
        placeholder: "Switch label",
      },
      {
        key: "checked",
        label: "Checked",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "reverse",
        label: "Reverse",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "file-input",
    label: "File Input",
    category: "forms",
    icon: "Upload",
    description: "File upload input",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Upload file",
        placeholder: "File input label",
      },
      {
        key: "helpText",
        label: "Help Text",
        type: "text",
        defaultValue: "Choose a file to upload",
        placeholder: "Help text",
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
    ],
  },
  {
    type: "input-group",
    label: "Input Group",
    category: "forms",
    icon: "Combine",
    description: "Input with prepended or appended content",
    properties: [
      {
        key: "label",
        label: "Label",
        type: "text",
        defaultValue: "Username",
        placeholder: "Field label",
      },
      {
        key: "prepend",
        label: "Prepend",
        type: "text",
        defaultValue: "@",
        placeholder: "Text before input",
      },
      {
        key: "append",
        label: "Append",
        type: "text",
        defaultValue: "",
        placeholder: "Text after input",
      },
      {
        key: "inputType",
        label: "Input Type",
        type: "select",
        defaultValue: "text",
        options: [
          { label: "Text", value: "text" },
          { label: "Email", value: "email" },
          { label: "Number", value: "number" },
          { label: "URL", value: "url" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },

  // ──────────────── BUTTONS ────────────────
  {
    type: "button",
    label: "Button",
    category: "buttons",
    icon: "MousePointerClick",
    description: "A clickable button",
    properties: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "Button",
        placeholder: "Button text",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Link", value: "link" },
        ],
      },
      {
        key: "outline",
        label: "Outline",
        type: "boolean",
        defaultValue: false,
        description: "Use outline style",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "disabled",
        label: "Disabled",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "block",
        label: "Full Width",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "iconLeft",
        label: "Icon (left)",
        type: "text",
        defaultValue: "",
        placeholder: "e.g. bi-house",
        description: "Bootstrap icon class",
      },
    ],
  },
  {
    type: "button-group",
    label: "Button Group",
    category: "buttons",
    icon: "MoreHorizontal",
    description: "Group of buttons together",
    properties: [
      {
        key: "buttons",
        label: "Buttons (comma-separated)",
        type: "text",
        defaultValue: "Left, Middle, Right",
        placeholder: "Button 1, Button 2, Button 3",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Info", value: "info" },
          { label: "Outline Primary", value: "outline-primary" },
          { label: "Outline Secondary", value: "outline-secondary" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "vertical",
        label: "Vertical",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },

  // ──────────────── NAVIGATION ────────────────
  {
    type: "navbar",
    label: "Navbar",
    category: "navigation",
    icon: "Menu",
    description: "Navigation bar",
    properties: [
      {
        key: "brand",
        label: "Brand / Logo",
        type: "text",
        defaultValue: "Navbar",
        placeholder: "Brand name",
      },
      {
        key: "items",
        label: "Nav Items (comma-separated)",
        type: "text",
        defaultValue: "Home, Features, Pricing, About",
        placeholder: "Home, About, Contact",
      },
      {
        key: "variant",
        label: "Color Scheme",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
        ],
      },
      {
        key: "expand",
        label: "Responsive Breakpoint",
        type: "select",
        defaultValue: "lg",
        options: [
          { label: "Always", value: "always" },
          { label: "sm", value: "sm" },
          { label: "md", value: "md" },
          { label: "lg", value: "lg" },
          { label: "xl", value: "xl" },
          { label: "xxl", value: "xxl" },
          { label: "Never", value: "never" },
        ],
      },
      {
        key: "bgColor",
        label: "Background",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Primary", value: "primary" },
          { label: "White", value: "white" },
          { label: "Transparent", value: "transparent" },
        ],
      },
      {
        key: "container",
        label: "Container",
        type: "select",
        defaultValue: "fluid",
        options: [
          { label: "Fluid", value: "fluid" },
          { label: "Container", value: "container" },
          { label: "None", value: "none" },
        ],
      },
    ],
  },
  {
    type: "nav-tabs",
    label: "Nav Tabs",
    category: "navigation",
    icon: "Columns",
    description: "Tab navigation",
    properties: [
      {
        key: "items",
        label: "Tab Items (comma-separated)",
        type: "text",
        defaultValue: "Home, Profile, Contact",
        placeholder: "Tab 1, Tab 2, Tab 3",
      },
      {
        key: "active",
        label: "Active Tab",
        type: "number",
        defaultValue: 0,
        description: "Index of active tab (0-based)",
      },
      {
        key: "style",
        label: "Style",
        type: "select",
        defaultValue: "tabs",
        options: [
          { label: "Tabs", value: "tabs" },
          { label: "Pills", value: "pills" },
          { label: "Underline", value: "underline" },
        ],
      },
      {
        key: "fill",
        label: "Fill",
        type: "select",
        defaultValue: "",
        options: [
          { label: "None", value: "" },
          { label: "Justified", value: "justify" },
          { label: "Fill", value: "fill" },
        ],
      },
      {
        key: "vertical",
        label: "Vertical",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "breadcrumb",
    label: "Breadcrumb",
    category: "navigation",
    icon: "ChevronRight",
    description: "Breadcrumb navigation",
    properties: [
      {
        key: "items",
        label: "Items (comma-separated)",
        type: "text",
        defaultValue: "Home, Library, Data",
        placeholder: "Home, Category, Page",
      },
    ],
  },
  {
    type: "pagination",
    label: "Pagination",
    category: "navigation",
    icon: "ChevronsLeftRight",
    description: "Pagination component",
    properties: [
      {
        key: "pages",
        label: "Total Pages",
        type: "number",
        defaultValue: 5,
      },
      {
        key: "active",
        label: "Active Page",
        type: "number",
        defaultValue: 1,
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
    ],
  },
  {
    type: "dropdown",
    label: "Dropdown",
    category: "navigation",
    icon: "ChevronsUpDown",
    description: "Dropdown menu",
    properties: [
      {
        key: "label",
        label: "Button Label",
        type: "text",
        defaultValue: "Dropdown button",
        placeholder: "Button text",
      },
      {
        key: "items",
        label: "Menu Items (one per line)",
        type: "textarea",
        defaultValue: "Action\nAnother action\nSomething else here\n---\nSeparated link",
        placeholder: "One item per line. Use --- for divider.",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Info", value: "info" },
          { label: "Outline Primary", value: "outline-primary" },
          { label: "Outline Secondary", value: "outline-secondary" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
        ],
      },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        defaultValue: "down",
        options: [
          { label: "Down", value: "down" },
          { label: "Up", value: "up" },
          { label: "End (right)", value: "end" },
          { label: "Start (left)", value: "start" },
        ],
      },
    ],
  },

  // ──────────────── CONTENT ────────────────
  {
    type: "card",
    label: "Card",
    category: "content",
    icon: "CreditCard",
    description: "A flexible content container",
    properties: [
      {
        key: "header",
        label: "Header",
        type: "text",
        defaultValue: "Featured",
        placeholder: "Card header text",
      },
      {
        key: "headerSize",
        label: "Header Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (0.75rem)", value: "sm" },
          { label: "Medium (0.875rem)", value: "md" },
          { label: "Large (1.25rem)", value: "lg" },
          { label: "Extra Large (1.5rem)", value: "xl" },
        ],
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        defaultValue: "Special title treatment",
        placeholder: "Card title",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "text",
        defaultValue: "Supporting text",
        placeholder: "Card subtitle",
      },
      {
        key: "text",
        label: "Body Text",
        type: "textarea",
        defaultValue:
          "Some quick example text to build on the card title and make up the bulk of the card's content.",
        placeholder: "Card body text",
      },
      {
        key: "footer",
        label: "Footer",
        type: "text",
        defaultValue: "2 days ago",
        placeholder: "Card footer text",
      },
      {
        key: "imgSrc",
        label: "Image URL",
        type: "text",
        defaultValue: "",
        placeholder: "https://picsum.photos/seed/card/400/200",
        description: "Add an image at the top of the card",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
      {
        key: "textAlign",
        label: "Text Alignment",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
      {
        key: "showButton",
        label: "Show Button",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "buttonText",
        label: "Button Text",
        type: "text",
        defaultValue: "Go somewhere",
        placeholder: "Button label",
      },
    ],
  },
  {
    type: "alert",
    label: "Alert",
    category: "content",
    icon: "AlertTriangle",
    description: "Alert message box",
    properties: [
      {
        key: "text",
        label: "Message",
        type: "textarea",
        defaultValue:
          "This is an important alert message. You should check it out!",
        placeholder: "Alert message",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        key: "dismissible",
        label: "Dismissible",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "heading",
        label: "Heading",
        type: "text",
        defaultValue: "",
        placeholder: "Optional heading",
      },
    ],
  },
  {
    type: "badge",
    label: "Badge",
    category: "content",
    icon: "Tag",
    description: "Small label or counter",
    properties: [
      {
        key: "text",
        label: "Text",
        type: "text",
        defaultValue: "New",
        placeholder: "Badge text",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        key: "pill",
        label: "Pill Shape",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "progress",
    label: "Progress Bar",
    category: "content",
    icon: "BarChart3",
    description: "Progress indicator",
    properties: [
      {
        key: "value",
        label: "Value (%)",
        type: "number",
        defaultValue: 60,
      },
      {
        key: "label",
        label: "Label",
        type: "boolean",
        defaultValue: false,
        description: "Show percentage label",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Success", value: "success" },
          { label: "Info", value: "info" },
          { label: "Warning", value: "warning" },
          { label: "Danger", value: "danger" },
          { label: "Striped", value: "striped" },
          { label: "Striped Animated", value: "animated" },
        ],
      },
      {
        key: "height",
        label: "Height (px)",
        type: "number",
        defaultValue: 0,
        description: "0 = default height",
      },
    ],
  },
  {
    type: "accordion",
    label: "Accordion",
    category: "content",
    icon: "ChevronsUpDown",
    description: "Collapsible accordion",
    properties: [
      {
        key: "items",
        label: "Items (use | to separate title and body)",
        type: "textarea",
        defaultValue:
          "Accordion Item #1|<strong>This is the first item's accordion body.</strong> It is shown by default.\nAccordion Item #2|<strong>This is the second item's accordion body.</strong> It is hidden by default.\nAccordion Item #3|<strong>This is the third item's accordion body.</strong> It is hidden by default.",
        placeholder: "Title|Body content",
        description: "Format: Title|Content (one item per line)",
      },
      {
        key: "flush",
        label: "Flush (no border)",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "alwaysOpen",
        label: "Always Open",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "spinner",
    label: "Spinner",
    category: "content",
    icon: "Loader2",
    description: "Loading spinner",
    properties: [
      {
        key: "type",
        label: "Type",
        type: "select",
        defaultValue: "border",
        options: [
          { label: "Border", value: "border" },
          { label: "Grow", value: "grow" },
        ],
      },
      {
        key: "variant",
        label: "Color",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
        ],
      },
      {
        key: "label",
        label: "Screen Reader Label",
        type: "text",
        defaultValue: "Loading...",
        placeholder: "Accessibility label",
      },
    ],
  },
  {
    type: "list-group",
    label: "List Group",
    category: "content",
    icon: "ListOrdered",
    description: "Styled list group",
    properties: [
      {
        key: "items",
        label: "Items (one per line)",
        type: "textarea",
        defaultValue:
          "Cras justo odio\nDapibus ac facilisis in\nMorbi leo risus\nPorta ac consectetur ac\nVestibulum at eros",
        placeholder: "One item per line",
      },
      {
        key: "flush",
        label: "Flush (no borders)",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "numbered",
        label: "Numbered",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "horizontal",
        label: "Horizontal",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "activeItem",
        label: "Active Item (0-based)",
        type: "number",
        defaultValue: -1,
        description: "Index of active item (-1 = none)",
      },
      {
        key: "disabledItem",
        label: "Disabled Item (0-based)",
        type: "number",
        defaultValue: -1,
        description: "Index of disabled item (-1 = none)",
      },
    ],
  },
  {
    type: "toast",
    label: "Toast",
    category: "content",
    icon: "Bell",
    description: "Push notification toast",
    properties: [
      {
        key: "title",
        label: "Title",
        type: "text",
        defaultValue: "Bootstrap",
        placeholder: "Toast title",
      },
      {
        key: "text",
        label: "Message",
        type: "textarea",
        defaultValue:
          "Hello, world! This is a toast message.",
        placeholder: "Toast message",
      },
      {
        key: "time",
        label: "Time",
        type: "text",
        defaultValue: "just now",
        placeholder: "e.g. 2 seconds ago",
      },
      {
        key: "variant",
        label: "Header Color",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
    ],
  },
  {
    type: "jumbotron",
    label: "Hero / Jumbotron",
    category: "content",
    icon: "PanelTop",
    description: "Hero section with call to action",
    properties: [
      {
        key: "title",
        label: "Title",
        type: "text",
        defaultValue: "Jumbotron Heading",
        placeholder: "Hero title",
      },
      {
        key: "lead",
        label: "Lead Text",
        type: "textarea",
        defaultValue:
          "This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.",
        placeholder: "Lead description",
      },
      {
        key: "buttonText",
        label: "Button Text",
        type: "text",
        defaultValue: "Learn more",
        placeholder: "CTA button text",
      },
      {
        key: "buttonVariant",
        label: "Button Variant",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        key: "secondaryButtonText",
        label: "Secondary Button",
        type: "text",
        defaultValue: "Secondary action",
        placeholder: "Optional secondary button",
      },
      {
        key: "bgColor",
        label: "Background",
        type: "select",
        defaultValue: "light",
        options: [
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Info", value: "info" },
          { label: "Success", value: "success" },
        ],
      },
      {
        key: "textAlign",
        label: "Text Alignment",
        type: "select",
        defaultValue: "center",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
    ],
  },
  {
    type: "carousel",
    label: "Carousel",
    category: "content",
    icon: "GalleryHorizontalEnd",
    description: "Image slideshow carousel",
    properties: [
      {
        key: "slides",
        label: "Slide Captions (one per line)",
        type: "textarea",
        defaultValue: "First slide label\nSecond slide label\nThird slide label",
        placeholder: "One caption per line",
      },
      {
        key: "controls",
        label: "Show Controls",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "indicators",
        label: "Show Indicators",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "dark",
        label: "Dark Variant",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "autoplay",
        label: "Autoplay",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    type: "modal",
    label: "Modal",
    category: "content",
    icon: "AppWindow",
    description: "Dialog modal (preview only)",
    properties: [
      {
        key: "title",
        label: "Title",
        type: "text",
        defaultValue: "Modal title",
        placeholder: "Modal title",
      },
      {
        key: "text",
        label: "Body Text",
        type: "textarea",
        defaultValue:
          "Modal body text goes here. You can add any content here.",
        placeholder: "Modal body",
      },
      {
        key: "showCloseButton",
        label: "Mostra pulsante Close",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "closeButtonText",
        label: "Testo pulsante Close",
        type: "text",
        defaultValue: "Close",
        placeholder: "Testo del pulsante close",
      },
      {
        key: "closeButtonStyle",
        label: "Stile pulsante Close",
        type: "select",
        defaultValue: "secondary",
        options: [
          { label: "Secondary", value: "secondary" },
          { label: "Primary", value: "primary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Outline Primary", value: "outline-primary" },
          { label: "Outline Secondary", value: "outline-secondary" },
          { label: "Outline Success", value: "outline-success" },
          { label: "Outline Danger", value: "outline-danger" },
          { label: "Outline Warning", value: "outline-warning" },
          { label: "Outline Info", value: "outline-info" },
          { label: "Link", value: "link" },
        ],
      },
      {
        key: "showPrimaryButton",
        label: "Mostra pulsante primario",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "footer",
        label: "Testo pulsante primario",
        type: "text",
        defaultValue: "Save Changes",
        placeholder: "Primary button text",
      },
      {
        key: "primaryButtonStyle",
        label: "Stile pulsante primario",
        type: "select",
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
          { label: "Light", value: "light" },
          { label: "Dark", value: "dark" },
          { label: "Outline Primary", value: "outline-primary" },
          { label: "Outline Secondary", value: "outline-secondary" },
          { label: "Outline Success", value: "outline-success" },
          { label: "Outline Danger", value: "outline-danger" },
          { label: "Outline Warning", value: "outline-warning" },
          { label: "Outline Info", value: "outline-info" },
          { label: "Link", value: "link" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Small (sm)", value: "sm" },
          { label: "Large (lg)", value: "lg" },
          { label: "Extra Large (xl)", value: "xl" },
        ],
      },
      {
        key: "centered",
        label: "Centered",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "scrollable",
        label: "Scrollable Body",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },

  {
    type: "offcanvas",
    label: "Offcanvas",
    category: "content",
    icon: "Sidebar",
    description: "Sidebar panel that slides in from the edge",
    properties: [
      {
        key: "title",
        label: "Title",
        type: "text",
        defaultValue: "Offcanvas",
        placeholder: "Offcanvas title",
      },
      {
        key: "text",
        label: "Body Text",
        type: "textarea",
        defaultValue:
          "Content goes here. You can place any component inside the offcanvas body.",
        placeholder: "Offcanvas body",
      },
      {
        key: "placement",
        label: "Placement",
        type: "select",
        defaultValue: "start",
        options: [
          { label: "Sinistra (start)", value: "start" },
          { label: "Destra (end)", value: "end" },
          { label: "Basso (bottom)", value: "bottom" },
          { label: "Alto (top)", value: "top" },
        ],
      },
      {
        key: "backdrop",
        label: "Backdrop",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "scrollBody",
        label: "Body Scroll",
        type: "boolean",
        defaultValue: false,
        description: "Allow body scrolling while offcanvas is open",
      },
    ],
  },

  // ──────────────── TABLES ────────────────
  {
    type: "table",
    label: "Table",
    category: "tables",
    icon: "Table",
    description: "Data table with embeddable components in cells",
    properties: [
      {
        key: "headers",
        label: "Headers (pipe-separated)",
        type: "text",
        defaultValue: "#|First|Last|Handle",
        placeholder: "Col 1|Col 2|Col 3",
      },
      {
        key: "numRows",
        label: "Data Rows",
        type: "number",
        defaultValue: 3,
      },
      {
        key: "striped",
        label: "Striped Rows",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "bordered",
        label: "Bordered",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "hover",
        label: "Hover Effect",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "condensed",
        label: "Small/Condensed",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
      {
        key: "stripedColumns",
        label: "Striped Columns",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "responsive",
        label: "Responsive",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    type: "table-row",
    label: "Table Row",
    category: "tables",
    icon: "TableRow",
    description: "Table data row (auto-managed)",
    hidden: true,
    properties: [],
  },
  {
    type: "table-cell",
    label: "Table Cell",
    category: "tables",
    icon: "TableCell",
    description: "Table cell — can contain components",
    hidden: true,
    properties: [
      {
        key: "text",
        label: "Testo cella",
        type: "text",
        defaultValue: "",
        placeholder: "Testo della cella",
      },
      {
        key: "align",
        label: "Allineamento",
        type: "select",
        defaultValue: "left",
        options: [
          { value: "left", label: "Sinistra" },
          { value: "center", label: "Centro" },
          { value: "right", label: "Destra" },
          { value: "justify", label: "Giustificato" },
        ],
      },
    ],
  },

  // ──────────────── IMAGES & MEDIA ────────────────
  {
    type: "image",
    label: "Image",
    category: "images",
    icon: "Image",
    description: "Responsive image",
    properties: [
      {
        key: "src",
        label: "Image URL",
        type: "text",
        defaultValue: "https://picsum.photos/seed/bseditor/800/400",
        placeholder: "https://...",
      },
      {
        key: "alt",
        label: "Alt Text",
        type: "text",
        defaultValue: "Description of image",
        placeholder: "Image description",
      },
      {
        key: "rounded",
        label: "Rounded Corners",
        type: "select",
        defaultValue: "",
        options: [
          { label: "None", value: "" },
          { label: "Rounded", value: "rounded" },
          { label: "Rounded Circle", value: "circle" },
          { label: "Thumbnail", value: "thumbnail" },
          { label: "Rounded Pill", value: "rounded-pill" },
        ],
      },
      {
        key: "fluid",
        label: "Fluid",
        type: "boolean",
        defaultValue: true,
        description: "Max-width 100% and auto height",
      },
    ],
  },
  {
    type: "figure",
    label: "Figure with Caption",
    category: "images",
    icon: "Frame",
    description: "Image with figure caption",
    properties: [
      {
        key: "src",
        label: "Image URL",
        type: "text",
        defaultValue: "https://picsum.photos/seed/figure/400/300",
        placeholder: "https://...",
      },
      {
        key: "caption",
        label: "Caption",
        type: "text",
        defaultValue: "A caption for the image.",
        placeholder: "Figure caption",
      },
      {
        key: "alignment",
        label: "Alignment",
        type: "select",
        defaultValue: "center",
        options: [
          { label: "Left", value: "start" },
          { label: "Center", value: "center" },
          { label: "Right", value: "end" },
        ],
      },
    ],
  },

  // ──────────────── UTILITIES ────────────────
  {
    type: "divider",
    label: "Divider (HR)",
    category: "utilities",
    icon: "Minus",
    description: "Horizontal rule divider",
    properties: [
      {
        key: "variant",
        label: "Variant",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
          { label: "Danger", value: "danger" },
          { label: "Info", value: "info" },
          { label: "Dark", value: "dark" },
          { label: "Light", value: "light" },
        ],
      },
      {
        key: "text",
        label: "Center Text",
        type: "text",
        defaultValue: "",
        placeholder: "Optional text in the middle",
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "select",
        defaultValue: "",
        options: [
          { label: "Default", value: "" },
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Success", value: "success" },
        ],
      },
    ],
  },
  {
    type: "spacer",
    label: "Spacer",
    category: "utilities",
    icon: "MoveVertical",
    description: "Empty vertical space",
    properties: [
      {
        key: "size",
        label: "Space (Bootstrap spacing)",
        type: "select",
        defaultValue: "4",
        options: [
          { label: "1 (0.25rem)", value: "1" },
          { label: "2 (0.5rem)", value: "2" },
          { label: "3 (1rem)", value: "3" },
          { label: "4 (1.5rem)", value: "4" },
          { label: "5 (3rem)", value: "5" },
          { label: "Auto", value: "auto" },
        ],
      },
    ],
  },
  {
    type: "embed-video",
    label: "Video Embed",
    category: "utilities",
    icon: "Video",
    description: "Responsive video embed (16:9 or 4:3)",
    properties: [
      {
        key: "ratio",
        label: "Aspect Ratio",
        type: "select",
        defaultValue: "16x9",
        options: [
          { label: "21:9", value: "21x9" },
          { label: "16:9", value: "16x9" },
          { label: "4:3", value: "4x3" },
          { label: "1:1", value: "1x1" },
        ],
      },
      {
        key: "url",
        label: "Video URL",
        type: "text",
        defaultValue: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        placeholder: "YouTube or other embed URL",
      },
    ],
  },
];

export function getComponentByType(
  type: string
): BootstrapComponentDefinition | undefined {
  return COMPONENTS.find((c) => c.type === type);
}

export function getComponentsByCategory(
  category: ComponentCategory
): BootstrapComponentDefinition[] {
  return COMPONENTS.filter((c) => c.category === category);
}
